
train_data_path: ../input/tamiloffensivehasoc/data_cleaned.csv
val_data_path: ../input/tamiloffensivehasoc/test_clen.csv
test_data_path: ../input/tamiloffensivehasoc/test_clen_transliterated.csv
train_text: review
train_label: label
val_text: review
val_label: label
test_text: tweets
test_label: label
save_model_path: tanglish_hasoc.bin
finetuned_model_path: tanglish_hasoc.bin
save_metrics_path: metrics.json
save_preds_path: preds.csv